services:
  picture-browser:
    image: picture-browser:8.5.4
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PICTURES_ROOT: /pictures
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - type: bind
        source: ${PICTURES_HOST_PATH:-./pictures}
        target: /pictures
        read_only: true
