ServerName picture-browser

<VirtualHost *:80>
    ServerName picture-browser
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        Options -Indexes
        AllowOverride None
        Require all granted
        DirectoryIndex disabled

        RewriteEngine On
        RewriteRule ^$ index.php [END]
        RewriteCond %{REQUEST_FILENAME} -f [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^ - [END]
        RewriteRule ^ /index.php [END]
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
