[PHP]
allow_url_fopen = Off
allow_url_include = Off
date.timezone = Europe/Berlin
display_errors = Off
display_startup_errors = Off
error_reporting = 24567
expose_php = Off
file_uploads = On
log_errors = Off
max_execution_time = 60
max_input_time = -1
memory_limit = 128M
post_max_size = 50M
upload_max_filesize = 50M

[opcache]
opcache.enable = On
opcache.enable_cli = On
opcache.jit = Off
opcache.memory_consumption = 128
opcache.revalidate_freq = 2
opcache.validate_timestamps = On
